{* Generated by Creative Elements, do not modify it *}
{ce_enqueue_miniature(13170101)}
<div data-elementor-type="product-miniature" data-elementor-id="13170101" class="elementor elementor-13170101{if !empty($productClasses)} {$productClasses}{/if}"><article class="elementor-section-wrap" data-id-product="{$product.id_product}" data-id-product-attribute="{$product.id_product_attribute}"><section class="elementor-element elementor-element-ebdfb72 elementor-section-boxed elementor-section-height-default elementor-section-height-default elementor-section elementor-top-section" data-id="ebdfb72" data-element_type="section" data-settings="{literal}{&quot;background_background&quot;:&quot;classic&quot;}{/literal}"><div class="elementor-container elementor-column-gap-default"><div class="elementor-row"><div class="elementor-element elementor-element-f922711 ce-valign-center elementor-column elementor-col-50 elementor-top-column" data-id="f922711" data-element_type="column"><div class="elementor-column-wrap elementor-element-populated"><div class="elementor-widget-wrap"><div class="elementor-element elementor-element-2a4d61e elementor-widget elementor-widget-product-miniature-image elementor-widget-image" data-id="2a4d61e" data-element_type="widget" data-widget_type="product-miniature-image.default"><div class="elementor-widget-container">{if $product.cover}{$image = $product.cover}{else}{$image = $urls.no_picture_image}{/if}
{$caption = ""}
{$image_by_size = $image.bySize['large_default']}
{$ratio = round($image_by_size.width / $image_by_size.height, 3)}
{$srcset = ["{$image_by_size.url} {$image_by_size.width}w"]}
{foreach $image.bySize as $size => $img}
{if 'large_default' !== $size && round($img.width / $img.height, 3) === $ratio}
{$srcset[] = "{$img.url} {$img.width}w"}
{/if}
{/foreach}
<div class="ce-product-image elementor-image">
{if $caption}
<figure class="ce-caption">
{/if}
<a href="{$product.url}"><img src="{$image_by_size.url}" srcset="{implode(', ', $srcset)}" alt="{$image.legend}"{if empty($loading_eager)} loading="lazy"{/if}
width="{$image_by_size.width}" height="{$image_by_size.height}"
sizes="(max-width: {$image_by_size.width}px) 100vw, {$image_by_size.width}px"></a>
{if $caption}
<figcaption class="widget-image-caption ce-caption-text">{$caption}</figcaption></figure>
{/if}
</div></div></div><div class="elementor-element elementor-element-e0d59b3 elementor-absolute ce-product-badges--inline elementor-widget elementor-widget-product-badges elementor-overflow-hidden" data-id="e0d59b3" data-element_type="widget" data-settings="{literal}{&quot;_position&quot;:&quot;absolute&quot;}{/literal}" data-widget_type="product-badges.default"><div class="elementor-widget-container"><div class="ce-product-badges">
{if !empty($product.flags['discount'])}
<div class="ce-product-badge ce-product-badge-sale">
{$product.flags['discount'].label}
</div>
{/if}
{if !empty($product.flags['new'])}
<div class="ce-product-badge ce-product-badge-new">
{$product.flags['new'].label}
</div>
{/if}
{if !empty($product.flags['pack'])}
<div class="ce-product-badge ce-product-badge-pack">
{$product.flags['pack'].label}
</div>
{/if}
{if !empty($product.flags['out_of_stock'])}
<div class="ce-product-badge ce-product-badge-out">
{$product.flags['out_of_stock'].label}
</div>
{/if}
{if !empty($product.flags['online-only'])}
<div class="ce-product-badge ce-product-badge-online">
{$product.flags['online-only'].label}
</div>
{/if}
</div></div></div></div></div></div><div class="elementor-element elementor-element-2772426 ce-valign-center elementor-column elementor-col-50 elementor-top-column" data-id="2772426" data-element_type="column"><div class="elementor-column-wrap elementor-element-populated"><div class="elementor-widget-wrap"><div class="elementor-element elementor-element-a32098c elementor-widget elementor-widget-product-miniature-name elementor-widget-heading" data-id="a32098c" data-element_type="widget" data-widget_type="product-miniature-name.default"><div class="elementor-widget-container"><h3 class="ce-product-name elementor-heading-title"><a href="{$product.url}">{$product.name}</a></h3></div></div><div class="elementor-element elementor-element-4a0e4aad elementor-star-rating--align-left elementor--star-style-star_fontawesome elementor-widget elementor-widget-product-miniature-rating elementor-widget-star-rating" data-id="4a0e4aad" data-element_type="widget" data-widget_type="product-miniature-rating.default"><div class="elementor-widget-container">
{$pcr = Context::getContext()->controller->getContainer()->get(product_comment_repository, 2)}
{if $pcr}
{$pcm = Configuration::get('PRODUCT_COMMENTS_MODERATE')}
{$nb_comments = $pcr->getCommentsNumber($product.id, $pcm)|intval}
{$average_grade = Tools::ps_round($pcr->getAverageGrade($product.id, $pcm), 1)}
<div class="ce-product-rating"><div class="elementor-star-rating__wrapper"><div class="elementor-star-rating" title="5/5"><i class="elementor-star-full">&#xF005;</i><i class="elementor-star-full">&#xF005;</i><i class="elementor-star-full">&#xF005;</i><i class="elementor-star-full">&#xF005;</i><i class="elementor-star-full">&#xF005;</i><span class="elementor-screen-only">5/5</span></div></div>
{if $nb_comments}
<span class="ce-product-rating__average-grade">{$average_grade}</span>
{/if}
</div>
{/if}
</div></div><div class="elementor-element elementor-element-5e4e454 ce-product-prices--layout-stacked elementor-widget elementor-widget-product-miniature-price elementor-overflow-hidden elementor-widget-product-price" data-id="5e4e454" data-element_type="widget" data-widget_type="product-miniature-price.default"><div class="elementor-widget-container">
{if $product.show_price}
<div class="ce-product-prices">
{if $product.has_discount}
{hook h='displayProductPriceBlock' product=$product type='old_price'}
<div class="ce-product-price-regular">{$product.regular_price}</div>
{/if}
{hook h='displayProductPriceBlock' product=$product type='before_price'}
{capture assign='ce_price'}{hook h='displayProductPriceBlock' product=$product type='custom_price' hook_origin='products_list'}{/capture}
<div class="ce-product-price{if $product.has_discount} ce-has-discount{/if}"><span>{if $ce_price}{$ce_price nofilter}{else}{$product.price}{/if}</span>
{if $product.has_discount}
{if 'percentage' === $product['discount_type']}
<span class="ce-product-badge ce-product-badge-sale ce-product-badge-sale-percentage">
{l s='Save %percentage%' sprintf=['%percentage%' => $product.discount_percentage_absolute] d='Shop.Theme.Catalog'}
</span>
{else}
<span class="ce-product-badge ce-product-badge-sale ce-product-badge-sale-amount">
{l s='Save %amount%' sprintf=['%amount%' => $product.discount_to_display] d='Shop.Theme.Catalog'}
</span>
{/if}
{/if}
</div>
{hook h='displayProductPriceBlock' product=$product type='weight'}
</div>
{/if}
</div></div><div class="elementor-element elementor-element-a9797d0 elementor-widget__width-auto elementor-widget elementor-widget-product-miniature-add-to-cart elementor-widget-button" data-id="a9797d0" data-element_type="widget" data-widget_type="product-miniature-add-to-cart.default"><div class="elementor-widget-container">{if $product.available_for_order && !$configuration.is_catalog}
<div class="elementor-button-wrapper"><a {if $product.add_to_cart_url}href="#ce-action=addToCart{if $product.minimal_quantity > 1}&amp;qty={$product.minimal_quantity}{/if}"{/if} class="elementor-button elementor-size-sm" role="button"><span class="elementor-button-content-wrapper"><span class="elementor-button-icon elementor-align-icon-left"><i class="" aria-hidden="true"></i></span><span class="elementor-button-text">Add to Cart</span></span></a></div>
{/if}</div></div><div class="elementor-element elementor-element-a6d204b elementor-widget__width-auto elementor-view-default elementor-widget elementor-widget-product-add-to-wishlist elementor-widget-icon" data-id="a6d204b" data-element_type="widget" data-widget_type="product-add-to-wishlist.default"><div class="elementor-widget-container">
{$atw_class = 'ce-add-to-wishlist'}
{$atw_icon = 'ceicon-heart-o'}
{if !isset($js_custom_vars.productsAlreadyTagged)}
{$js_custom_vars.productsAlreadyTagged = []}
{$js_custom_vars.blockwishlistController = {url entity='module' name='blockwishlist' controller='action'}}
{/if}
{foreach $js_custom_vars.productsAlreadyTagged as $tagged}
{if $tagged.id_product == $product.id && $tagged.id_product_attribute == $product.id_product_attribute}
{$atw_icon = 'ceicon-heart'}
{$atw_class = 'ce-add-to-wishlist elementor-active'}
{break}
{/if}
{/foreach}
<div class="elementor-icon-wrapper"><a class="elementor-icon {$atw_class}" data-product-id="{$product.id}" data-product-attribute-id="{$product.id_product_attribute}" href="{$js_custom_vars.blockwishlistController}"><i class="{$atw_icon}" aria-hidden="true"></i></a></div></div></div></div></div></div></div></div></section></article></div>