<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'crisp.ps_accounts_installer' shared service.

return $this->services['crisp.ps_accounts_installer'] = new \PrestaShop\PsAccountsInstaller\Installer\Installer('5.0');
