<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2vhljk3\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2vhljk3/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2vhljk3.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2vhljk3\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2vhljk3\appProdProjectContainer([
    'container.build_hash' => '2vhljk3',
    'container.build_id' => '9b61d161',
    'container.build_time' => 1737221730,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2vhljk3');
