<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVydhbxh\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVydhbxh/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVydhbxh.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVydhbxh\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVydhbxh\appDevDebugProjectContainer([
    'container.build_hash' => 'Vydhbxh',
    'container.build_id' => '85adde0f',
    'container.build_time' => 1737216748,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVydhbxh');
