<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJutbm7f\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJutbm7f/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJutbm7f.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJutbm7f\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJutbm7f\appProdProjectContainer([
    'container.build_hash' => 'Jutbm7f',
    'container.build_id' => 'fb333d29',
    'container.build_time' => 1737221745,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJutbm7f');
