<?php
/**
 * Copyright ETS Software Technology Co., Ltd
 *
 * NOTICE OF LICENSE
 *
 * This file is not open source! Each license that you purchased is only available for 1 website only.
 * If you want to use this file on more websites (or projects), you need to purchase additional licenses.
 * You are not allowed to redistribute, resell, lease, license, sub-license or offer our resources to any third party.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
 * versions in the future.
 *
 * @author ETS Software Technology Co., Ltd
 * @copyright  ETS Software Technology Co., Ltd
 * @license    Valid for 1 website (or project) for each purchase of license
*/

namespace PrestaShop\Module\EtsAutoUpgrade\TaskRunner\Rollback;

use PrestaShop\Module\EtsAutoUpgrade\Parameters\UpgradeFileNames;
use PrestaShop\Module\EtsAutoUpgrade\TaskRunner\AbstractTask;

/**
 * Only displays the success message.
*/
class RollbackComplete extends AbstractTask
{
    public function run()
    {
        $this->logger->info($this->translator->trans('Restoration process done. Congratulations! You can now reactivate your shop.', array(), 'Modules.Etsupgrade.Admin'));
        $this->next = '';

        // Set default configs.
        $configs = $this->container->getUpgradeConfiguration();
        $configs->merge($this->container->getUpgradeConfigurationStorage()->getDefaultData());
        $this->container->getUpgradeConfigurationStorage()->save($configs, UpgradeFileNames::CONFIG_FILENAME);
    }

    public function init()
    {
	     // TODO: Change the autogenerated stub
    }
}
