<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIqv99fi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIqv99fi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIqv99fi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIqv99fi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIqv99fi\appDevDebugProjectContainer([
    'container.build_hash' => 'Iqv99fi',
    'container.build_id' => 'bd3e4f41',
    'container.build_time' => 1737216752,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIqv99fi');
